export const tripData = [
  {
    id: 1,
    name: "Japan Adventure",
    date: "Oct 1–10, 2025",
    location: "Japan",
    type: "Adventure",
    locationType: "City & Mountain",
    description:
      "Explore Japan's vibrant cities and scenic mountains. Experience culture, food, and adventure all in one trip.",
    recommendedGear: [
      "Comfortable shoes",
      "Camera",
      "Light jacket",
      "Travel guidebook",
    ],
    activities: [
      "Sightseeing",
      "Hiking Mount Fuji",
      "Temple visits",
      "Food tasting",
    ],
    bestTravelTime: "March - May, September - November",
    duration: "10 days",
    image:
      "https://images.unsplash.com/photo-1579525108311-0c5730b5799d?q=80&w=1470&auto=format&fit=crop",
  },
  {
    id: 2,
    name: "Paris Getaway",
    date: "Dec 20–30, 2025",
    location: "Paris, France",
    type: "Leisure",
    locationType: "City",
    description:
      "Romantic getaway to the city of lights. Explore iconic landmarks, museums, and cafes.",
    recommendedGear: [
      "Camera",
      "Comfortable walking shoes",
      "Warm clothing",
      "Travel guidebook",
    ],
    activities: [
      "Eiffel Tower visit",
      "Seine river cruise",
      "Museum tours",
      "Café hopping",
    ],
    bestTravelTime: "April - June, September - November",
    duration: "10 days",
    image:
      "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?q=80&w=1473&auto=format&fit=crop",
  },
  {
    id: 3,
    name: "London Explorer",
    date: "Nov 5–15, 2025",
    location: "London, UK",
    type: "Cultural",
    locationType: "City",
    description:
      "Discover London's rich history and modern attractions. Enjoy landmarks, theaters, and shopping.",
    recommendedGear: ["Umbrella", "Comfortable shoes", "Travel card", "Camera"],
    activities: [
      "Sightseeing",
      "Theater show",
      "Museum visits",
      "River Thames cruise",
    ],
    bestTravelTime: "April - June, September - October",
    duration: "11 days",
    image:
      "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?q=80&w=1470&auto=format&fit=crop",
  },
  {
    id: 4,
    name: "New York City Trip",
    date: "Sep 10–20, 2025",
    location: "New York, USA",
    type: "Leisure",
    locationType: "City",
    description:
      "Experience the hustle and bustle of NYC, with iconic landmarks, Broadway shows, and shopping.",
    recommendedGear: [
      "Comfortable shoes",
      "Camera",
      "Metro card",
      "Light jacket",
    ],
    activities: [
      "Statue of Liberty",
      "Times Square",
      "Central Park",
      "Broadway Show",
    ],
    bestTravelTime: "April - June, September - November",
    duration: "11 days",
    image:
      "https://images.unsplash.com/photo-1546436836-07a91091f160?q=80&w=1474&auto=format&fit=crop",
  },
  {
    id: 5,
    name: "Sydney Adventure",
    date: "Oct 15–25, 2025",
    location: "Sydney, Australia",
    type: "Adventure",
    locationType: "City & Beach",
    description:
      "Combine urban exploration with beach relaxation. Enjoy Sydney's iconic sites and coastal beauty.",
    recommendedGear: ["Swimwear", "Sunscreen", "Comfortable shoes", "Camera"],
    activities: [
      "Sydney Opera House",
      "Bondi Beach",
      "Harbour Bridge Climb",
      "Surfing",
    ],
    bestTravelTime: "September - November, March - May",
    duration: "11 days",
    image:
      "https://images.unsplash.com/photo-1523428096881-5bd79d043006?q=80&w=1470&auto=format&fit=crop",
  },
  {
    id: 6,
    name: "Rome Holiday",
    date: "Nov 1–10, 2025",
    location: "Rome, Italy",
    type: "Cultural",
    locationType: "City",
    description:
      "Dive into ancient history and vibrant street life in Rome. Explore museums, churches, and piazzas.",
    recommendedGear: [
      "Comfortable shoes",
      "Camera",
      "Light clothing",
      "Travel guidebook",
    ],
    activities: ["Colosseum", "Vatican City", "Pantheon", "Piazza Navona"],
    bestTravelTime: "April - June, September - October",
    duration: "10 days",
    image:
      "https://images.unsplash.com/photo-1555992828-ca4dbe41d294?q=80&w=764&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: 7,
    name: "Iceland Northern Lights",
    date: "Dec 5–15, 2025",
    location: "Iceland",
    type: "Adventure",
    locationType: "Mountain & Icefield",
    description:
      "Witness the breathtaking Northern Lights and explore Iceland's unique landscapes.",
    recommendedGear: [
      "Warm clothing",
      "Camera",
      "Hiking boots",
      "Thermal wear",
    ],
    activities: [
      "Northern Lights spotting",
      "Hot springs",
      "Glacier hiking",
      "Waterfall tours",
    ],
    bestTravelTime: "September - March",
    duration: "11 days",
    image:
      "https://images.unsplash.com/photo-1517928260182-5688aead3066?q=80&w=1470&auto=format&fit=crop",
  },
  {
    id: 8,
    name: "Bali Retreat",
    date: "Oct 20–30, 2025",
    location: "Bali, Indonesia",
    type: "Leisure",
    locationType: "Beach & Island",
    description:
      "Relax on the stunning beaches of Bali and enjoy cultural experiences with locals.",
    recommendedGear: ["Swimwear", "Sunscreen", "Light clothing", "Camera"],
    activities: [
      "Beach lounging",
      "Temple visits",
      "Yoga retreats",
      "Snorkeling",
    ],
    bestTravelTime: "April - October",
    duration: "11 days",
    image:
      "https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=1470&auto=format&fit=crop",
  },
  {
    id: 9,
    name: "Dubai Luxury Tour",
    date: "Nov 15–25, 2025",
    location: "Dubai, UAE",
    type: "Luxury",
    locationType: "City & Desert",
    description:
      "Experience modern luxury and desert adventures in Dubai. Shop, dine, and explore iconic skyscrapers.",
    recommendedGear: [
      "Light clothing",
      "Sunscreen",
      "Camera",
      "Comfortable shoes",
    ],
    activities: [
      "Burj Khalifa",
      "Desert Safari",
      "Dubai Mall",
      "Luxury dining",
    ],
    bestTravelTime: "November - March",
    duration: "11 days",
    image:
      "https://lh3.googleusercontent.com/gpms-cs-s/AB8u6HaOdlGfDvI9kDzm7zVYz9eQKT1Lnt1vaGHK3J16VF900T9SWcikvCskB_a1SJ5o2BPi-f7V0su-AUzKAEjLvKNX4bnqG-V18JYETG73PDiFhdEVnOLt_gq0yJlGWbRvhRB1MyWz=s680-w680-h510-rw",
  },
  {
    id: 10,
    name: "Thailand Beaches",
    date: "Dec 1–10, 2025",
    location: "Thailand",
    type: "Leisure",
    locationType: "Beach",
    description:
      "Relax and enjoy pristine beaches, vibrant markets, and local cuisine in Thailand.",
    recommendedGear: ["Swimwear", "Sunscreen", "Hat", "Camera"],
    activities: [
      "Beach activities",
      "Island hopping",
      "Thai cooking class",
      "Snorkeling",
    ],
    bestTravelTime: "November - February",
    duration: "10 days",
    image:
      "https://plus.unsplash.com/premium_photo-1697730197947-f19e92f0035b?q=80&w=1470&auto=format&fit=crop",
  },
  {
    id: 11,
    name: "Canadian Rockies",
    date: "Sep 20–30, 2025",
    location: "Canada",
    type: "Adventure",
    locationType: "Mountain",
    description:
      "Explore majestic mountains, lakes, and wildlife in the Canadian Rockies.",
    recommendedGear: ["Hiking boots", "Camera", "Warm clothing", "Backpack"],
    activities: ["Hiking", "Wildlife spotting", "Photography", "Camping"],
    bestTravelTime: "June - September",
    duration: "11 days",
    image:
      "https://images.unsplash.com/photo-1587381419916-78fc843a36f8?q=80&w=1470&auto=format&fit=crop",
  },
  {
    id: 12,
    name: "Santorini Escape",
    date: "Oct 5–15, 2025",
    location: "Santorini, Greece",
    type: "Leisure",
    locationType: "Island",
    description:
      "Enjoy romantic sunsets, whitewashed houses, and crystal-clear waters in Santorini.",
    recommendedGear: ["Light clothing", "Camera", "Sunscreen", "Swimwear"],
    activities: [
      "Sunset views",
      "Wine tasting",
      "Boat tours",
      "Beach relaxation",
    ],
    bestTravelTime: "April - October",
    duration: "11 days",
    image:
      "https://images.unsplash.com/photo-1678266561093-324802646fb2?q=80&w=735&auto=format&fit=crop",
  },
  {
    id: 13,
    name: "Morocco Adventure",
    date: "Nov 10–20, 2025",
    location: "Morocco",
    type: "Adventure",
    locationType: "Desert & City",
    description:
      "Explore colorful markets, desert landscapes, and traditional Moroccan culture.",
    recommendedGear: ["Comfortable shoes", "Hat", "Camera", "Light clothing"],
    activities: [
      "Desert camel ride",
      "Market visits",
      "City tour",
      "Cooking class",
    ],
    bestTravelTime: "March - May, September - November",
    duration: "11 days",
    image:
      "https://images.unsplash.com/photo-1569383746724-6f1b882b8f46?q=80&w=1470&auto=format&fit=crop",
  },
  {
    id: 14,
    name: "Alaskan Cruise",
    date: "Sep 25–Oct 5, 2025",
    location: "Alaska, USA",
    type: "Cruise",
    locationType: "Sea & Mountain",
    description:
      "Sail through Alaska's stunning fjords and glaciers while enjoying wildlife and nature.",
    recommendedGear: ["Warm clothing", "Camera", "Binoculars", "Rain jacket"],
    activities: [
      "Cruise tour",
      "Wildlife spotting",
      "Glacier viewing",
      "Photography",
    ],
    bestTravelTime: "May - September",
    duration: "11 days",
    image:
      "https://images.unsplash.com/photo-1605978221138-0be1cae9204b?q=80&w=1470&auto=format&fit=crop",
  },
  {
    id: 15,
    name: "Vietnam Discovery",
    date: "Oct 10–20, 2025",
    location: "Vietnam",
    type: "Cultural",
    locationType: "City & Countryside",
    description:
      "Discover Vietnam's rich culture, cuisine, and landscapes from cities to countryside.",
    recommendedGear: ["Comfortable shoes", "Camera", "Light clothing", "Hat"],
    activities: [
      "City tours",
      "Food tasting",
      "River cruises",
      "Countryside exploration",
    ],
    bestTravelTime: "February - April, August - October",
    duration: "11 days",
    image:
      "https://images.unsplash.com/photo-1531737212413-667205e1cda7?q=80&w=734&auto=format&fit=crop",
  },
  {
    id: 16,
    name: "Egypt Pyramids Tour",
    date: "Nov 20–30, 2025",
    location: "Egypt",
    type: "Cultural",
    locationType: "Desert & City",
    description:
      "Explore the ancient wonders of Egypt, including the Pyramids and the Nile River.",
    recommendedGear: ["Comfortable shoes", "Hat", "Sunscreen", "Camera"],
    activities: [
      "Pyramids visit",
      "Nile cruise",
      "Museum tours",
      "Market shopping",
    ],
    bestTravelTime: "October - April",
    duration: "11 days",
    image:
      "https://plus.unsplash.com/premium_photo-1664303467567-17891a27998a?q=80&w=1476&auto=format&fit=crop",
  },
  {
    id: 17,
    name: "Brazil Carnival",
    date: "Dec 10–20, 2025",
    location: "Brazil",
    type: "Festival",
    locationType: "City",
    description:
      "Experience the world-famous Rio Carnival with colorful parades, music, and dance.",
    recommendedGear: ["Comfortable shoes", "Camera", "Light clothing", "Hat"],
    activities: [
      "Carnival parades",
      "Beach visits",
      "Samba shows",
      "City sightseeing",
    ],
    bestTravelTime: "February - March",
    duration: "11 days",
    image:
      "https://images.unsplash.com/photo-1742541922679-95cc82ba6c7d?q=80&w=880&auto=format&fit=crop",
  },
  {
    id: 18,
    name: "Greece Island Hopping",
    date: "Oct 25–Nov 5, 2025",
    location: "Greece",
    type: "Leisure",
    locationType: "Island",
    description:
      "Explore multiple Greek islands, enjoy beaches, local cuisine, and historical sites.",
    recommendedGear: [
      "Swimwear",
      "Camera",
      "Light clothing",
      "Comfortable shoes",
    ],
    activities: [
      "Island hopping",
      "Beach activities",
      "Historical tours",
      "Food tasting",
    ],
    bestTravelTime: "May - October",
    duration: "12 days",
    image:
      "https://images.unsplash.com/photo-1498503182468-3b51cbb6cb24?q=80&w=1470&auto=format&fit=crop",
  },
  {
    id: 19,
    name: "South Africa Safari",
    date: "Nov 5–15, 2025",
    location: "South Africa",
    type: "Adventure",
    locationType: "Wildlife & Savanna",
    description:
      "Experience thrilling safaris, wildlife spotting, and beautiful landscapes in South Africa.",
    recommendedGear: ["Binoculars", "Camera", "Hat", "Comfortable shoes"],
    activities: [
      "Safari tours",
      "Wildlife photography",
      "Nature hikes",
      "Cultural visits",
    ],
    bestTravelTime: "May - September",
    duration: "11 days",
    image:
      "https://images.unsplash.com/photo-1481889617387-82a8f2413b6b?q=80&w=1471&auto=format&fit=crop",
  },
  {
    id: 20,
    name: "Hawaii Beach Trip",
    date: "Dec 15–25, 2025",
    location: "Hawaii, USA",
    type: "Leisure",
    locationType: "Beach & Island",
    description:
      "Relax on Hawaii’s beautiful beaches, explore volcanoes, and enjoy tropical adventures.",
    recommendedGear: ["Swimwear", "Sunscreen", "Camera", "Hiking shoes"],
    activities: ["Beach activities", "Volcano tours", "Snorkeling", "Hiking"],
    bestTravelTime: "April - October",
    duration: "11 days",
    image:
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1473&auto=format&fit=crop",
  },
];
